### ISSUE TITLE
debug_train.csv file not found

### ISSUE THREAD

**Issue by rmh1480** [xinyangz/ltrn#1]
Hi Xinyang,

I am getting error that seems to point to a local file in your environment.  

run_amazon.sh
FileNotFoundError: [Errno 2] No such file or directory: '/data1/xinyang/debug_train.csv'

This is referenced in:
bert/dataset.py:      df_train.to_csv("/data1/xinyang/debug_train.csv")

Should this be replaced with train_docs.csv or is there another file needed?

Best regards,
Raja

**Comment by xinyangz** [comment]
Thanks for reaching out. This is a debug line that I included accidentally. Please remove it or pull from the latest repo.

**Comment by rmh1480** [comment]
Thank you so much for the quick response.  It's training now.

Best,
Raja
